# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49a525474fe07ded0768f0443b37dc8e91bc23992f651a70c3a7921639ce0a2bace565cdaf884050b456400343abeaf5c8c93bca70adae790e759b7bc5c71ebe

test:
  secret_key_base: 26cbef56340ab3c85518cd0907798a8e1ddb8a0c6a3f080b39f9a3847def9c4c82df0c266a9373a3bbdaff1c820f6da962ea23f6db9399d786f66434160844cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
